Complete design change and change of controls using  dash-bootstrap
bcdev/doors-dashboards pull request #25
Opened 2024-02-14 16:37 UTC by ruchimotwaniBC

2024-02-16 15:11 UTC, TonioF requested changes
The module dashboard.py has become unnecessary. Please remove it, or better, replace its content with that of dashboard_bootstrap.py and delete that one. Also, have a look at #26 and my other comments.

2024-02-16 15:11 UTC, TonioF commented on doors_dashboards/components/scatterplot.py
> +                        text='Sampling Depth [M]'.title(),
```suggestion
                        text=levels[-1].title(),
```

2024-02-16 15:11 UTC, TonioF commented on doors_dashboards/components/scatterplot.py
> +            fig.update_yaxes(title_text=variables[1].title())
```suggestion
            fig.update_xaxes(title_text=x_variable.title())
            fig.update_yaxes(title_text=y_variable.title())
```

2024-02-16 15:16 UTC, ruchimotwaniBC commented
> The module dashboard.py has become unnecessary. Please remove it, or better, replace its content with that of dashboard_bootstrap.py and delete that one. 

I have already done it in my new branch created from this. Shall I do it in this branch and commit it??

2024-02-16 16:02 UTC, TonioF commented
> > The module dashboard.py has become unnecessary. Please remove it, or better, replace its content with that of dashboard_bootstrap.py and delete that one.
> 
> I have already done it in my new branch created from this. Shall I do it in this branch and commit it??

Yes, please.

2024-02-19 16:22 UTC, TonioF approved these changes

2024-02-19 16:23 UTC, merged